WITH CombinedResults AS (
    SELECT 'AUDIT' AS Source, colno, COLNAME, TYPENAME, LENGTH, SCALE
FROM (select COLNO, COLNAME, TYPENAME, LENGTH, SCALE from syscat.columns where TABSCHEMA = 'AUDIT' and TABNAME = 'AUDIT') 
    UNION ALL
    SELECT 'AUDITOLD' AS Source, colno, COLNAME, TYPENAME, LENGTH, SCALE
    FROM (select COLNO, COLNAME, TYPENAME, LENGTH, SCALE from syscat.columns where TABSCHEMA = 'AUDIT' and TABNAME = 'AUDITOLD') 
)
SELECT Source, colno, COLNAME, TYPENAME, LENGTH, SCALE
FROM CombinedResults
GROUP BY Source, colno, COLNAME, TYPENAME, LENGTH, SCALE
HAVING COUNT(DISTINCT colno) = 2;
